---
baseurl: "https://ig.nore.me/"
title: "ig.nore.me"
LanguageCode: en
Author:
  Name: Arjen Schwarz
  Email: arjen@ig.nore.me
  TwitterPage: "https://www.twitter.com/ArjenSchwarz"
  Avatar: "https://ig.nore.me/img/profilepicsmall.jpg"
  GitHub: "ArjenSchwarz"
permalinks:
  posts: /:year/:month/:slug/
  linkposts: /:year/:month/:slug/
  pages: /:slug/
  presentations: /presentations/:year/:month/:slug
  weeklynotes: /weekly-notes/:slug/
params:
  Subtitle: "Connecting the dots"
taxonomies:
  category: "categories"
  series: "series"
  project: "projects"
MetaDataFormat: yaml
disqusShortname: ignoreme
pygmentsCodeFences: true
pygmentsStyle: native
Paginate: 10
outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  links:
    mediaType: "application/json"
    baseName: "links"
    isPlainText: true
outputs:
  home:
    - "html"
    - "rss"
    - "jsonfeed"
    - "links"
  page:
    - "html"
menu:
  main:
      - Name: "Projects"
        Identifier: "projects"
        Url: "/projects/"
        Weight: 2
      - Name: "Presentations"
        Identifier: "presentations"
        Url: "/presentations/"
        Weight: 3
