---
baseurl: "http://ig.nore.me/"
title: "ig.nore.me"
permalinks:
  posts: /:year/:month/:slug/
  linkposts: /:year/:month/:slug/
  pages: /:slug/
params:
  Subtitle: "Connecting the dots"
  AuthorName: "Arjen Schwarz"
  GitHubUser: "ArjenSchwarz"
taxonomies:
  category: "categories"
MetaDataFormat: yaml
disqusShortname: ignoreme
Paginate: 10