---
baseurl: "https://ig.nore.me/"
title: "ig.nore.me"
preserveTaxonomyNames: true
LanguageCode: en
Author:
  Name: Arjen Schwarz
  Email: arjen@ig.nore.me
  TwitterPage: "https://www.twitter.com/ArjenSchwarz"
  Avatar: "https://ig.nore.me/img/profilepic_arjen_2018_square.jpg"
  GitHub: "ArjenSchwarz"
permalinks:
  posts: /:year/:month/:slug/
  linkposts: /:year/:month/:slug/
  pages: /:slug/
  presentations: /presentations/:year/:month/:slug
  videos: /videos/:year/:month/:slug
  weeklynotes: /weekly-notes/:slug/
params:
  Subtitle: "Connecting the dots"
  mainSections: [posts, presentations, videos, weeklynotes, linkposts]
taxonomies:
  category: "categories"
  series: "series"
  project: "projects"
  authors: "authors"
MetaDataFormat: yaml
disqusShortname: ignoreme
pygmentsCodeFences: true
pygmentsStyle: native
Paginate: 15
outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  links:
    mediaType: "application/json"
    baseName: "links"
    isPlainText: true
  search:
    mediaType: "application/json"
    baseName: "search"
    isPlainText: true
outputs:
  home:
    - "html"
    - "rss"
    - "jsonfeed"
    - "links"
    - "search"
  page:
    - "html"
menu:
  main:
      - Name: "Projects"
        Identifier: "projects"
        Url: "/projects/"
        Weight: 2
      - Name: "Videos"
        Identifier: "videos"
        Url: "/videos/"
        Weight: 3
      - Name: "Presentations"
        Identifier: "presentations"
        Url: "/presentations/"
        Weight: 4
related:
  threshold: 80
  toLower: true
  includeNewer: true
  indices:
    - name: projects
      weight: 200
    - name: keywords
      weight: 150
    - name: categories
      weight: 50
