---
baseurl: "http://ig.nore.me/"
title: "ig.nore.me"
permalinks:
  posts: /:year/:month/:slug/
  linkposts: /:year/:month/:slug/
  pages: /:slug/
  presentations: /presentations/:year/:month/:slug
params:
  Subtitle: "Connecting the dots"
  AuthorName: "Arjen Schwarz"
  GitHubUser: "ArjenSchwarz"
taxonomies:
  category: "categories"
  series: "series"
MetaDataFormat: yaml
disqusShortname: ignoreme
Paginate: 10
menu:
  main:
      - Name: "Home"
        Identifier: "home"
        Url: "/"
        Weight: 1
      - Name: "Series"
        Identifier: "series"
        Url: "/series/"
        Weight: 2
      - Name: "Presentations"
        Identifier: "presentations"
        Url: "/presentations/"
        Weight: 3