---
baseurl: "http://ig.nore.me/"
title: "ig.nore.me"
permalinks:
  posts: /:year/:month/:slug/
  linkposts: /:year/:month/:slug/
  pages: /:title
params:
  Subtitle: "Connecting the dots"
  AuthorName: "Arjen Schwarz"
  GitHubUser: "ArjenSchwarz"
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5
taxonomies:
  category: "categories"
MetaDataFormat: yaml
disqusShortname: ignoreme